# Generated by Django 5.0.2 on 2024-05-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_year_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
