# Generated by Django 5.0.2 on 2024-05-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_user_date_expired_user_sem_1_user_sem_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='payment-qr/')),
            ],
        ),
    ]
