# Generated by Django 5.0.2 on 2024-05-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='acct_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
