# Generated by Django 5.0.2 on 2024-05-13 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_officeryear_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='abous_us_context/')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutiveBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='executive_banner/')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.officeryear')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='social_media_assistant/')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_head', models.CharField(blank=True, max_length=100, null=True)),
                ('social_media_head_img', models.ImageField(blank=True, null=True, upload_to='social_media_head/')),
                ('assistants', models.ManyToManyField(to='app.documentationassistant')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.officeryear')),
            ],
        ),
        migrations.CreateModel(
            name='VisionMissionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.CharField(blank=True, max_length=255, null=True)),
                ('mission', models.CharField(blank=True, max_length=255, null=True)),
                ('goal', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutUsDesc',
        ),
    ]
