# Generated by Django 5.0.2 on 2024-05-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_aboutusdesc_officeryear_multimediateam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationteam',
            name='role_assistant_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentationteam',
            name='role_assistant_10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentationteam',
            name='role_assistant_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentationteam',
            name='role_assistant_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentationteam',
            name='role_assistant_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentationteam',
            name='role_assistant_5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentationteam',
            name='role_assistant_6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentationteam',
            name='role_assistant_7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentationteam',
            name='role_assistant_8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='documentationteam',
            name='role_assistant_9',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='esportsteam',
            name='role_assistant_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='esportsteam',
            name='role_assistant_10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='esportsteam',
            name='role_assistant_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='esportsteam',
            name='role_assistant_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='esportsteam',
            name='role_assistant_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='esportsteam',
            name='role_assistant_5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='esportsteam',
            name='role_assistant_6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='esportsteam',
            name='role_assistant_7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='esportsteam',
            name='role_assistant_8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='esportsteam',
            name='role_assistant_9',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='multimediateam',
            name='role_assistant_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='multimediateam',
            name='role_assistant_10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='multimediateam',
            name='role_assistant_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='multimediateam',
            name='role_assistant_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='multimediateam',
            name='role_assistant_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='multimediateam',
            name='role_assistant_5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='multimediateam',
            name='role_assistant_6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='multimediateam',
            name='role_assistant_7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='multimediateam',
            name='role_assistant_8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='multimediateam',
            name='role_assistant_9',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='programmingteam',
            name='role_assistant_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='programmingteam',
            name='role_assistant_10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='programmingteam',
            name='role_assistant_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='programmingteam',
            name='role_assistant_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='programmingteam',
            name='role_assistant_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='programmingteam',
            name='role_assistant_5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='programmingteam',
            name='role_assistant_6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='programmingteam',
            name='role_assistant_7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='programmingteam',
            name='role_assistant_8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='programmingteam',
            name='role_assistant_9',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='writersteam',
            name='role_assistant_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='writersteam',
            name='role_assistant_10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='writersteam',
            name='role_assistant_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='writersteam',
            name='role_assistant_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='writersteam',
            name='role_assistant_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='writersteam',
            name='role_assistant_5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='writersteam',
            name='role_assistant_6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='writersteam',
            name='role_assistant_7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='writersteam',
            name='role_assistant_8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='writersteam',
            name='role_assistant_9',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
