# Generated by Django 5.0.2 on 2024-05-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_aboutuscontext_executivebanner_socialmediaassistant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediateam',
            name='assistants',
            field=models.ManyToManyField(to='app.socialmediaassistant'),
        ),
    ]
