# Generated by Django 5.0.2 on 2024-05-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_socialmediateam_assistants'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutuscontext',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
