# Generated by Django 5.0.2 on 2024-05-18 05:19

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_marketingteamassistant_adviser_boardmember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpic',
            name='image',
            field=models.ImageField(storage=app.models.PublicMediaStorage(), upload_to='about-pic-upload/'),
        ),
        migrations.AlterField(
            model_name='aboutuscontext',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=app.models.PublicMediaStorage(), upload_to='abous_us_context/'),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=app.models.PublicMediaStorage(), upload_to='adviser/'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=app.models.PublicMediaStorage(), upload_to='board_members/'),
        ),
        migrations.AlterField(
            model_name='documentationassistant',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=app.models.PublicMediaStorage(), upload_to='documentation_assistant/'),
        ),
        migrations.AlterField(
            model_name='documentationteam',
            name='documentation_head_img',
            field=models.ImageField(blank=True, null=True, storage=app.models.PublicMediaStorage(), upload_to='documentation_head/'),
        ),
        migrations.AlterField(
            model_name='esportsassistant',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=app.models.PublicMediaStorage(), upload_to='esports_assistant/'),
        ),
        migrations.AlterField(
            model_name='esportsteam',
            name='esports_head_img',
            field=models.ImageField(blank=True, null=True, storage=app.models.PublicMediaStorage(), upload_to='esports_head/'),
        ),
        migrations.AlterField(
            model_name='executivebanner',
            name='image',
            field=models.ImageField(blank=True, storage=app.models.PublicMediaStorage(), upload_to='executive_banner/'),
        ),
        migrations.AlterField(
            model_name='executiveofficer',
            name='assistant_secretary_img',
            field=models.ImageField(blank=True, storage=app.models.PublicMediaStorage(), upload_to='assistant_secretary'),
        ),
        migrations.AlterField(
            model_name='executiveofficer',
            name='assistant_treasurer_img',
            field=models.ImageField(blank=True, storage=app.models.PublicMediaStorage(), upload_to='assistant_treasurer'),
        ),
        migrations.AlterField(
            model_name='executiveofficer',
            name='auditor_img',
            field=models.ImageField(blank=True, storage=app.models.PublicMediaStorage(), upload_to='auditor'),
        ),
        migrations.AlterField(
            model_name='executiveofficer',
            name='president_img',
            field=models.ImageField(blank=True, storage=app.models.PublicMediaStorage(), upload_to='president'),
        ),
        migrations.AlterField(
            model_name='executiveofficer',
            name='pro_img',
            field=models.ImageField(blank=True, storage=app.models.PublicMediaStorage(), upload_to='pro'),
        ),
        migrations.AlterField(
            model_name='executiveofficer',
            name='secretary_img',
            field=models.ImageField(blank=True, storage=app.models.PublicMediaStorage(), upload_to='secretary'),
        ),
        migrations.AlterField(
            model_name='executiveofficer',
            name='treasurer_img',
            field=models.ImageField(blank=True, storage=app.models.PublicMediaStorage(), upload_to='treasurer'),
        ),
        migrations.AlterField(
            model_name='executiveofficer',
            name='vp_external_img',
            field=models.ImageField(blank=True, storage=app.models.PublicMediaStorage(), upload_to='vp_external'),
        ),
        migrations.AlterField(
            model_name='executiveofficer',
            name='vp_internal_img',
            field=models.ImageField(blank=True, storage=app.models.PublicMediaStorage(), upload_to='vp_internal'),
        ),
        migrations.AlterField(
            model_name='highlightsevent',
            name='image',
            field=models.ImageField(storage=app.models.PublicMediaStorage(), upload_to='highlights-event/'),
        ),
        migrations.AlterField(
            model_name='marketingteam',
            name='marketing_team_img',
            field=models.ImageField(blank=True, null=True, storage=app.models.PublicMediaStorage(), upload_to='marketing_team/'),
        ),
        migrations.AlterField(
            model_name='marketingteamassistant',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=app.models.PublicMediaStorage(), upload_to='marketing_team_assistant/'),
        ),
        migrations.AlterField(
            model_name='multimediaassistant',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=app.models.PublicMediaStorage(), upload_to='multimedia_assistant/'),
        ),
        migrations.AlterField(
            model_name='multimediateam',
            name='multimedia_head_img',
            field=models.ImageField(blank=True, null=True, storage=app.models.PublicMediaStorage(), upload_to='multimedia_head/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='image',
            field=models.ImageField(storage=app.models.PublicMediaStorage(), upload_to='payment-qr/'),
        ),
        migrations.AlterField(
            model_name='programmingassistant',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=app.models.PublicMediaStorage(), upload_to='programming_assistant/'),
        ),
        migrations.AlterField(
            model_name='programmingteam',
            name='programming_head_img',
            field=models.ImageField(blank=True, null=True, storage=app.models.PublicMediaStorage(), upload_to='programming_head/'),
        ),
        migrations.AlterField(
            model_name='socialmediaassistant',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=app.models.PublicMediaStorage(), upload_to='social_media_assistant/'),
        ),
        migrations.AlterField(
            model_name='socialmediateam',
            name='social_media_head_img',
            field=models.ImageField(blank=True, null=True, storage=app.models.PublicMediaStorage(), upload_to='social_media_head/'),
        ),
        migrations.AlterField(
            model_name='softwaretools',
            name='image',
            field=models.ImageField(storage=app.models.PublicMediaStorage(), upload_to='software-tools/'),
        ),
        migrations.AlterField(
            model_name='softwaretoolsresource',
            name='image',
            field=models.ImageField(storage=app.models.PublicMediaStorage(), upload_to='software-resources/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=app.models.PublicMediaStorage(), upload_to='profile-images/'),
        ),
        migrations.AlterField(
            model_name='writersassistant',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=app.models.PublicMediaStorage(), upload_to='writers_assistant/'),
        ),
        migrations.AlterField(
            model_name='writersteam',
            name='writers_head_img',
            field=models.ImageField(blank=True, null=True, storage=app.models.PublicMediaStorage(), upload_to='writers_head/'),
        ),
    ]
