from django.contrib import admin
from .models import *
# Register your models here.

admin.site.register(Banner)
admin.site.register(AboutPic)
admin.site.register(HighlightsEvent)
admin.site.register(SoftwareTools)
admin.site.register(User)
admin.site.register(SoftwareToolsResource)
admin.site.register(OfficerYear)
admin.site.register(ExecutiveBanner)
admin.site.register(ExecutiveOfficer)
admin.site.register(MultimediaTeam)
admin.site.register(MultimediaAssistant)
admin.site.register(ProgrammingTeam)
admin.site.register(ProgrammingAssistant)
admin.site.register(WritersTeam)
admin.site.register(WritersAssistant)
admin.site.register(DocumentationTeam)
admin.site.register(DocumentationAssistant)
admin.site.register(EsportsTeam)
admin.site.register(EsportsAssistant)
admin.site.register(SocialMediaTeam)
admin.site.register(SocialMediaAssistant)
admin.site.register(Adviser)
admin.site.register(BoardMember)
admin.site.register(MarketingTeam)
admin.site.register(MarketingTeamAssistant)